Grammatically updated the doc.
chaoss/augur pull request #1668
Opened 2022-03-26 11:04 UTC by rooby786

There was a small grammar mistake in welcome message. 

-Welcome to the Augur project's official documentation. Below is a brief primer on the project and its goals; if you're new to the project, we recommend giving it _**a**_ once-over as a gentle introduction. Otherwise, feel free to hop right into the docs!
+Welcome to the Augur project's official documentation. Below is a brief primer on the project and its goals; if you're new to the project, we recommend giving it _**an**_ once-over as a gentle introduction. Otherwise, feel free to hop right into the docs!

2022-03-26 18:10 UTC, diananova commented
"a once-over" is correct, no need to change it.

2022-04-04 16:31 UTC, sgoggins requested changes

2022-04-04 16:31 UTC, sgoggins commented on docs/source/index.rst
> -Welcome to the Augur project's official documentation. Below is a brief primer on the project and its goals; if you're new to the project, we recommend giving it a once-over as a gentle introduction.
The grammar is tricky, but it is actually correct how it is. 

https://www.quickanddirtytips.com/education/grammar/a-versus-an

2022-04-14 14:42 UTC, sgoggins commented on docs/source/index.rst
> +Welcome to the Augur project's official documentation. Below is a brief primer on the project and its goals; if you're new to the project, we recommend giving it an once-over as a gentle introduction
"a", not "an" is grammatically correct in this case.

2022-04-14 14:43 UTC, merged