Resolving issue 1696
chaoss/augur pull request #1797
Opened 2022-04-21 15:36 UTC by Preshh0

Resolving [issue 1696](https://github.com/chaoss/augur/issues/1696)
Fixed a welcome guide for newcomers in the getting started dir.
In this PR:

- I wrote out a more detailed onboarding process for newcomers.
- Added images for better understanding
- Correctly referenced the issue this PR is supposed to resolve.

2022-04-22 08:08 UTC, sgoggins commented
@Preshh0 : It looks like you've committed cloned repositories here: `[workers/facade_worker/augur_facade/](https://github.com/chaoss/augur/pull/1797/files#diff-5f4378d21bfc35284b8ded339112675299ed0738e7dec1eae541b123e58eb480)` ... Those cloned repos from our test repositories should not be committed to Augur source code.

2022-04-22 08:08 UTC, sgoggins requested changes
Remove directory: `workers/facade_worker/augur_facade/`

2022-04-22 23:07 UTC, Preshh0 commented
On it!

2022-06-08 23:29 UTC, sgoggins approved these changes

2022-06-08 23:30 UTC, merged