feat: Added task to collect repository traffic
chaoss/augur pull request #2098
Opened 2022-12-27 11:35 UTC by meetagrawal09

**Description**
- The PR adds a task to collect Github repository traffic data (specifically repository clone history data)
- Github API docs - https://docs.github.com/en/rest/metrics/traffic#get-repository-clones
This PR fixes #1468 , #1373 

**Signed commits**
- [X] Yes, I signed my commits.

2022-12-29 15:20 UTC, sgoggins requested changes
This is a pretty fallow week for us, but I think there are a couple schema migration related changes requested you could work on, or ask for help with. 

@ABrain7710 : Can you look at this PR?

2022-12-30 14:03 UTC, meetagrawal09 commented on augur/application/db/models/augur_data.py
> +
I have auto-generated the schema migration script from the model `RepoClass` that I had defined, using the command `alembic revision --autogenerate --rev-id "3" -m "traffic additions"` 

Do let me know if I need to roll-back changes to the `augur_full.sql` and if the model class in `augur_data.py` needs to be placed in a separate file

2023-01-02 10:08 UTC, meetagrawal09 commented on augur/application/schema/augur_full.sql
> +-- Name: repo_clones_id_seq; Type: SEQUENCE; Schema: augur_data; Owner: augur
@sgoggins can you please guide me as to what tool is used for schema migration scripts here or if the alembic version file generated would be the one sufficient.

2023-01-21 14:20 UTC, merged

2023-02-24 03:58 UTC, sgoggins commented
@ABrain7710 : I need to sit down with you to finish merging this. There's a schema change file that's out of order with work that happened since this was created.