Code Complexity API Update
chaoss/augur pull request #2105
Opened 2023-01-01 18:18 UTC by sgoggins

NEW API endpoints for code complexity

2023-01-02 18:34 UTC, ABrain7710 requested changes
The `tests/test_routes/test_complexity_routes.py` file needs to be refactored to match the new tests for api routes. I could do this

2023-02-14 17:32 UTC, sgoggins commented
@ABrain7710 : If you could fix the tests that would be great!

2023-02-17 21:33 UTC, IsaacMilarky approved these changes

2023-02-24 04:02 UTC, sgoggins commented
@ABrain7710 : How much work is updating the tests to cover the new strategy?

2023-03-20 22:26 UTC, ABrain7710 approved these changes

2023-03-20 23:14 UTC, merged