Remove the use of shell for mkdir -p
chaoss/augur pull request #2314
Opened 2023-04-12 13:41 UTC by mscherer

See https://stackoverflow.com/questions/600268/mkdir-p-functionality-in-python

**Description**

This PR fixes a problem I bumped into while deploying (eg, the container do not work without /bin in PATH). I have a workaround for my setup, but it is better to fix the root cause.

**Notes for Reviewers**

**Signed commits**
- [X] Yes, I signed my commits.

2023-04-12 17:36 UTC, IsaacMilarky requested changes
Just missing some exception handling.

2023-04-12 17:36 UTC, IsaacMilarky commented on augur/tasks/git/util/facade_worker/facade_worker/facade05repofetch.py
> +        pathlib.Path(repo_path).mkdir(parents=True, exist_ok=True)
This is a good change however it should still catch any exceptions Path.mkdir raises and respond like how it did before when we didn't get a return code. It should update its internal logs when it is unable to create the directory.

2023-04-12 17:36 UTC, IsaacMilarky commented on augur/tasks/git/util/facade_worker/facade_worker/facade05repofetch.py
> +        pathlib.Path(repo_path).mkdir(parents=True, exist_ok=True)
Just put the mkdir line in a try/except block and put the body of the if statement on line 123 in the exception handle. Otherwise looks good.

2023-04-12 18:18 UTC, IsaacMilarky approved these changes
Looks good to me now.

2023-04-14 19:38 UTC, sgoggins reviewed
@IsaacMilarky / @ABrain7710 : Could you go ahead and review this?

2023-04-14 20:03 UTC, ABrain7710 approved these changes

2023-04-14 20:04 UTC, merged