fix constraint issues with secondary and facade collection hooks
chaoss/augur pull request #2339
Opened 2023-04-20 20:37 UTC by IsaacMilarky

**Description**
Fix constraints on the collection_status table to reflect edge cases of collection.

**Signed commits**
- [ ] Yes, I signed my commits.

2023-04-20 20:44 UTC, sgoggins submitted a review, later dismissed
LGTM. I think @ABrain7710 should also check it so he knows what's changed.

2023-04-20 20:50 UTC, ABrain7710 requested changes
After thinking about the core and secondary dependency check. I think it should just test the negative case rather than specifying all the different positive cases. So I think it should just be `NOT(core_status = 'Pending' AND secondary_status='Collecting')`, so we ensure that the secondary status isn't collecting when the core status is pending. I think the rest of cases are valid

2023-04-20 21:20 UTC, ABrain7710 commented on augur/application/db/models/augur_operations.py
>              name='core_secondary_dependency_check'
I'm getting really confused on this check. Wouldn't this be the one case we want to restrict?
`NOT(core_status = 'Pending' AND secondary_status='Collecting')`

2023-04-20 21:28 UTC, ABrain7710 commented
@IsaacMilarky I think it would be good if we listed out all the cases we are wanting to avoid. Then write a boolean expression that matches each case. Then all we would have to do is wrap each case in NOT and place an OR in between each. I'm having a lot of trouble going through and wrapping my head around these conversions and I think there are some errors. So I think it would be best if we used this simple structure of 
Not(invalid case) OR NOT(invalid_case) OR NOT(invalid_case) within each check

2023-04-21 18:32 UTC, ABrain7710 approved these changes
LGTM

2023-04-21 18:34 UTC, merged