[API] add pull_requests_new endpoint to get time series of new PRs opened
chaoss/augur pull request #2544
Opened 2023-10-07 06:49 UTC by Shiva953

**Description**
- This PR is adds a `pull_requests_new` API endpoint, which aligns with the existing endpoints for issues and contributors. This new feature allows users to retrieve time series data on the number of new PRs opened within a specified time frame for a given repository. 

This PR addresses #2542 

**Notes for Reviewers**

**Signed commits**
- [x] Yes, I signed my commits.

2023-10-10 06:50 UTC, Shiva953 commented
@ABrain7710 any updates?

2023-10-15 16:09 UTC, sgoggins requested changes
@Shiva953 : We need you to add the API documentation for these endpoints as well. They are located in the `docs/source/rest-api/spec.yml` file. Thank you!!!

2023-10-30 14:08 UTC, IsaacMilarky approved these changes

2023-10-31 13:58 UTC, sgoggins approved these changes

2023-10-31 13:58 UTC, merged