Upgrade SQLAlchemy to 2.0.22 and Pandas to 1.5.3
chaoss/augur pull request #2572
Opened 2023-10-30 17:42 UTC by IsaacMilarky

**Description**
- Update SQLAlchemy to version 2.0.22
- Update Pandas to version 1.5.3
- Removed redundant ORM Relationship definitions
- Fix MacOS not finding location of go
- Fix Alembic env.py not working
- Fix broken util endpoints

This PR fixes #2557 #2556

**Signed commits**
- [x] Yes, I signed my commits.

2023-10-30 19:29 UTC, Ulincsys commented on augur/api/view/utils.py
> +with DatabaseEngine() as engine:
I think it's fine to merge for testing, but before this makes it into main, we need to ensure that the repo load controller gets updated with the below syntax (or something similar). This is just here for testing, and is not intended to be final

2023-10-31 19:09 UTC, ABrain7710 requested changes
I think all the `engine.connect()` should be using a context manager to ensure the connection is being disposed of. I also don't think we should be removing valid relationships from the orm as this removes functionality without any benefit that I can see

2023-10-31 19:09 UTC, ABrain7710 commented on augur/application/db/models/augur_operations.py
> +    #group = relationship("UserGroup")
These are not redundant. `repo = relationship("Repo")` still needs to be present on the UserRepo class to enable to ability to do UserRepo.repo and get back the related Repo object. Placing a relationship on the UserRepo relationship on the Repo class has no effect on the UserRepo class.

2023-10-31 19:09 UTC, ABrain7710 commented on augur/tasks/data_analysis/insight_worker/tasks.py
> +            result = engine.connect().execute(deleteSQL)
Similar to what I mentioned in another comment. I think we should use `with engine.connect()` to make sure the connection is disposed afterwards

2023-11-01 17:29 UTC, ABrain7710 requested changes
There are still a few context managers missing for the  `engine.connect()`. Also the `process_ossf_dependency_metrics` needs to stay in the secondary collection

2023-11-01 17:29 UTC, ABrain7710 commented on augur/api/metrics/pull_request.py
> +            results = pd.read_sql(commitNewContributor, engine.connect(),
This should use the `conn` variable that is defined by the context manager

2023-11-01 17:29 UTC, ABrain7710 commented on augur/application/db/models/augur_operations.py
> +    #user = relationship("User")
This is still commented out

2023-11-01 17:29 UTC, ABrain7710 commented on augur/tasks/data_analysis/insight_worker/tasks.py
> +    result = engine.connect().execute(delete_points_SQL, repo_id=repo_id, min_date=min_date)
Needs context manager

2023-11-01 17:29 UTC, ABrain7710 commented on augur/tasks/data_analysis/insight_worker/tasks.py
> +        result = engine.connect().execute(deleteSQL)
Needs context manager

2023-11-01 17:29 UTC, ABrain7710 commented on augur/tasks/data_analysis/insight_worker/tasks.py
> +        result = engine.connect().execute(deleteSQL)
Needs context manager

2023-11-01 17:29 UTC, ABrain7710 commented on augur/tasks/data_analysis/insight_worker/tasks.py
> +                    result = engine.connect().execute(deleteSQL)
Needs context manager

2023-11-01 17:29 UTC, ABrain7710 commented on augur/tasks/start_tasks.py
> +        process_ossf_dependency_metrics.si(repo_git)
This needs to stay in the secondary collection since it has a decorator of `@celery.task(base=AugurSecondaryRepoCollectionTask)
`

2023-11-01 17:48 UTC, ABrain7710 approved these changes
Looks good

2023-11-01 18:01 UTC, merged