Fix RabbitMQ config issue in Docker
chaoss/augur pull request #2739
Opened 2024-03-13 22:05 UTC by Ulincsys

**Description**
- Change RabbitMQ configuration scheme
  - Add `definitions.json` to contain default user, password, and vhost definitions
  - Add `update_config.py` to convert Docker args to RabbitMQ config items
    - NOTE: RabbitMQ ignores *all* envvars if *any* config file is present
  - I'm not sure if the original `augur.conf` is doing anything anymore, but there's no reason to get rid of it as of right now
- Add `update_config.py`
  - Pull Docker args and check that they exist
  - Compute password hash with `rabbitmqctl`
    - AFAICT RabbitMQ does not support plain-text passwords in a config file
  - load default `definitions.json`, update with new values and write changes
- Provide default `advanced.config`
  - Previously we were creating this file with `RUN echo ...`
  - Extra entries are required in this file to enable loading of `definitions.json`
- In `docker-compose.yml`
  - Move `environment` section to `args` section, update formatting
  - Make default vhost configurable (defaults to same, `augur_vhost`)
- In `rabbitmq/Dockerfile`
  - Import default args
  - Import new config files described above
  - Add Python to container, and run the config updater at build time

**Signed commits**
- [x] Yes, I signed my commits.

2024-03-13 22:46 UTC, IsaacMilarky requested changes
There is one `subprocess.run` call in the build that can fail silently as well as some other minor linting suggestions. Otherwise looks great and is greatly needed.

2024-03-13 22:46 UTC, IsaacMilarky commented on docker/rabbitmq/update_config.py
> +hash_processor = subprocess.run(f"rabbitmqctl hash_password {rabbit_pass}".split(),
We should probably set check to `True` here so it doesn't fail silently.

2024-03-13 22:48 UTC, IsaacMilarky commented on docker/rabbitmq/update_config.py
> +hash_processor = subprocess.run(f"rabbitmqctl hash_password {rabbit_pass}".split(),
https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/subprocess-run-check.html

2024-03-13 22:50 UTC, IsaacMilarky commented
Oh I just saw that it checks the return code never mind.

2024-03-13 22:51 UTC, IsaacMilarky approved these changes

2024-03-14 13:28 UTC, sgoggins approved these changes
LGTM

2024-03-14 13:28 UTC, merged