Release Ready
chaoss/augur pull request #2812
Opened 2024-06-07 15:10 UTC by sgoggins

**Description**
- Completed Testing

This PR fixes #
- issue #2787 
- issue #2786 
- issue #2785 
- issue #2752 
- issue #2656 
- issue #2542 
- issue #2439 
- issue #2289 

**Signed commits**
- [x] Yes, I signed my commits.

2024-06-07 15:16 UTC, sgoggins commented
There are some typos, mostly related to `absoulte` as a spelling for `absolute`, but lets just let it ride since the error is a variable name and consistent throughout. At least for this release.

2024-06-07 20:10 UTC, Ulincsys requested changes
Double-checking the linter output aired some issues, and also a few spelling mistakes that should be fixed.

2024-06-09 02:41 UTC, sgoggins commented on augur/application/db/lib.py
> +def facade_bulk_insert_commits(logger, records):
@ABrain7710

2024-06-10 23:44 UTC, Ulincsys approved these changes

2024-06-10 23:44 UTC, IsaacMilarky approved these changes
Looks good for the most part.

2024-06-10 23:44 UTC, IsaacMilarky commented on augur/tasks/github/util/github_task_session.py
> +        #self.oauths = GithubRandomKeyAuth(self, logger) # Removed and replaced for the issue below in frontend.py
?

2024-06-10 23:45 UTC, merged